name: Main

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug/release/both)'
        required: true
        default: 'both'

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Configure build
        run: |
          echo "org.gradle.jvmargs=-Xmx2048m" >> gradle.properties
          echo "org.gradle.caching=true" >> gradle.properties

      - name: Build Release
        if: ${{ inputs.build_type == 'both' || inputs.build_type == 'release' }}
        run: ./gradlew :app:assembleRelease --no-daemon --stacktrace

      - name: Build Debug
        if: ${{ inputs.build_type == 'both' || inputs.build_type == 'debug' }}
        run: ./gradlew :app:assembleDebug --no-daemon --stacktrace

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: apk-files
          path: |
            app/build/apk/release/*.apk
            app/build/apk/debug/*.apk
          if-no-files-found: error
