name: Main

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '.github/ISSUE_TEMPLATE/**'
      - '.github/workflows/issue.yml'
      - '**.md'
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build type (debug/release/both)'
        required: true
        default: 'both'
      skip_telegram:
        description: 'Skip Telegram notification (true/false)'
        required: false
        default: 'false'

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Write key
        if: (github.event_name != 'pull_request' && github.ref == 'refs/heads/master') || github.event_name == 'workflow_dispatch'
        run: |
          mkdir -p app/src/main/assets
          echo officialBuild=true >> local.properties
          echo buildWithGitSuffix=true >> local.properties
          echo storePassword='${{ secrets.KEY_STORE_PASSWORD }}' >> local.properties
          echo keyAlias='${{ secrets.ALIAS }}' >> local.properties
          echo keyPassword='${{ secrets.ALIAS_KEY_PASSWORD }}' >> local.properties
          echo fileDir=`pwd`/key.jks >> local.properties
          echo "${{ secrets.KEY_STORE }}" | base64 -d > key.jks
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 -d > app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: |
          ./gradlew :app:assemble${{ inputs.build_type == 'both' ? 'Release assembleDebug' : inputs.build_type }} \
            --no-daemon \
            --stacktrace \
            --info \
            --scan

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-build-outputs
          path: |
            app/build/apk/
            app/build/outputs/mapping/release/
          if-no-files-found: error

      - name: Post to Telegram
        if: ${{ (github.event_name != 'pull_request' && github.ref == 'refs/heads/master') || (github.event_name == 'workflow_dispatch' && inputs.skip_telegram != 'true') }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHANNEL }}
          message: |
            *Build Completed* ✅
            - Workflow: ${{ github.workflow }}
            - Commit: ${{ github.sha }}
            - Result: ${{ job.status }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
